#ifndef COMMON_INCLUDE_OBC_ERRORS_H_
#define COMMON_INCLUDE_OBC_ERRORS_H_

typedef enum {
    /* Common Errors 0 - 99 */
    OBC_ERR_CODE_SUCCESS = 0,
    OBC_ERR_CODE_UNKNOWN = 1,
    OBC_ERR_CODE_INVALID_ARG = 2,
    OBC_ERR_CODE_QUEUE_FULL = 3,
    OBC_ERR_CODE_MUTEX_TIMEOUT = 4,
    OBC_ERR_CODE_BUFF_TOO_SMALL = 5,
    OBC_ERR_CODE_LOG_MSG_SILENCED = 6,
    OBC_ERR_CODE_TASK_CREATION_FAILED = 7,
    OBC_ERR_CODE_TIMER_CREATION_FAILED = 8,

    /* Driver Errors 100 - 150 */
    OBC_ERR_CODE_GENERAL_SCI_FAILED = 100,
    OBC_ERR_CODE_SCI_SEND_FAILED = 101,
    OBC_ERR_CODE_SCI_MUTEX_INIT_FAILED = 103,
    OBC_ERR_CODE_SCI_MUTEX_TIMEOUT = 104,
} obc_error_code_t;

#endif // COMMON_INCLUDE_OBC_ERRORS_H_